[Metadata]
Name=darkshell
Version=1
Author=vader
Description=Shell-matched hairline dark theme (quickshell darkshell/niri)
ScaleWithDPI=True

[InputPanel]
NormalColor=#e6e0e9
HighlightCandidateColor=#e6e0e9
HighlightColor=#e6e0e9
HighlightBackgroundColor=#1d1b20
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=6
Right=6
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Image=panel.png

[InputPanel/Background/Margin]
Left=12
Right=12
Top=12
Bottom=12

[InputPanel/Highlight]
Image=highlight.png

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor=#e6e0e9
HighlightCandidateColor=#e6e0e9

[Menu/Background]
Image=panel.png

[Menu/Background/Margin]
Left=12
Right=12
Top=12
Bottom=12

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Image=highlight.png

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#272727

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=6
Right=6
Top=5
Bottom=5
